language: node_js
node_js:
  - "7"
  - "6"
install: npm install && lerna bootstrap
script:
  - node --harmony "$(npm bin)/jest" --coverage
  - node --harmony "$(npm bin)/jest"
  - npm --prefix "packages/gulp-restructure-tree" run build
after_success: 'yarn run coveralls'
